[build]
buildCommand = "npm install --prefix frontend --include=dev && npm run build --prefix frontend && npm install --prefix backend && npx prisma generate --schema=backend/prisma/schema.prisma"

[deploy]
startCommand = "cd backend && npx prisma migrate deploy && node src/app.js"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
